language: generic
sudo: required
services: 
    - docker


before_install:
    - docker build -t emigdion13/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true emigdion13/docker-react npm run test
